/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import static Presentacion.frmMain.PanelPrincipal;
import java.awt.CardLayout;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;

/**
 *
 * @author Administrador
 */
public class frmMain1 extends javax.swing.JFrame {

  CardLayout vista;
    frmAsistencia frmA = new frmAsistencia();

  
    public frmMain1() {
        initComponents();
        pegarImagenes();
        this.setLocationRelativeTo(null);
        vista = (CardLayout) PanelPrincipal.getLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        btncerrar = new javax.swing.JButton();
        btncerrar1 = new javax.swing.JButton();
        btncerrar2 = new javax.swing.JButton();
        lbusuario = new javax.swing.JLabel();
        lbusuario1 = new javax.swing.JLabel();
        btnhome = new javax.swing.JButton();
        btnnotas = new javax.swing.JButton();
        btnasistencia = new javax.swing.JButton();
        btnreportes = new javax.swing.JButton();
        lbusuario2 = new javax.swing.JLabel();
        lbusuario3 = new javax.swing.JLabel();
        PanelPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setPreferredSize(new java.awt.Dimension(900, 160));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });

        btncerrar.setBackground(new java.awt.Color(0, 0, 0));
        btncerrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btncerrar.setContentAreaFilled(false);
        btncerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncerrarActionPerformed(evt);
            }
        });

        btncerrar1.setBackground(new java.awt.Color(0, 0, 0));
        btncerrar1.setContentAreaFilled(false);
        btncerrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncerrar1ActionPerformed(evt);
            }
        });

        btncerrar2.setBackground(new java.awt.Color(0, 0, 0));
        btncerrar2.setContentAreaFilled(false);
        btncerrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncerrar2ActionPerformed(evt);
            }
        });

        lbusuario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbusuario.setForeground(new java.awt.Color(255, 255, 255));
        lbusuario.setText("Usuario:");

        lbusuario1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbusuario1.setForeground(new java.awt.Color(255, 255, 255));
        lbusuario1.setText("José Luis Arias Flores");

        btnhome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnhome.setForeground(new java.awt.Color(255, 255, 255));
        btnhome.setText("HOME");
        btnhome.setContentAreaFilled(false);
        btnhome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnhome.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnhome.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnhome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnhomemauseclicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnhomemouseexited(evt);
            }
        });
        btnhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomeActionPerformed(evt);
            }
        });

        btnnotas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnnotas.setForeground(new java.awt.Color(255, 255, 255));
        btnnotas.setText("NOTAS");
        btnnotas.setContentAreaFilled(false);
        btnnotas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnnotas.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnnotas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnnotas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnnotasmauseclicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnnotasmouseexited(evt);
            }
        });
        btnnotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnotasActionPerformed(evt);
            }
        });

        btnasistencia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnasistencia.setForeground(new java.awt.Color(255, 255, 255));
        btnasistencia.setText("ASISTENCIA");
        btnasistencia.setContentAreaFilled(false);
        btnasistencia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnasistencia.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnasistencia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnasistencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnasistenciamauseclicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnasistenciamouseexited(evt);
            }
        });
        btnasistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnasistenciaActionPerformed(evt);
            }
        });

        btnreportes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnreportes.setForeground(new java.awt.Color(255, 255, 255));
        btnreportes.setText("REPORTES");
        btnreportes.setContentAreaFilled(false);
        btnreportes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnreportes.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnreportes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnreportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnreportesmauseclicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnreportesmouseexited(evt);
            }
        });
        btnreportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreportesActionPerformed(evt);
            }
        });

        lbusuario2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbusuario2.setForeground(new java.awt.Color(255, 255, 255));
        lbusuario2.setText("Cargo:");

        lbusuario3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbusuario3.setForeground(new java.awt.Color(255, 255, 255));
        lbusuario3.setText("Admin");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btnhome, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lbusuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbusuario1)
                        .addGap(105, 105, 105)
                        .addComponent(lbusuario2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbusuario3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                        .addComponent(btncerrar2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btncerrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btncerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnasistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnnotas, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnreportes, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btncerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncerrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncerrar2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbusuario)
                    .addComponent(lbusuario1)
                    .addComponent(lbusuario2)
                    .addComponent(lbusuario3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnreportes, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnhome, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnnotas, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnasistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        PanelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        PanelPrincipal.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncerrarActionPerformed
        dispose();
    }//GEN-LAST:event_btncerrarActionPerformed

    private void btncerrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncerrar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncerrar1ActionPerformed

    private void btncerrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncerrar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncerrar2ActionPerformed

    private void btnhomemauseclicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhomemauseclicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhomemauseclicked

    private void btnhomemouseexited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhomemouseexited

    }//GEN-LAST:event_btnhomemouseexited

    private void btnhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomeActionPerformed

        //  PanelPrincipal.setVisible(true);
    }//GEN-LAST:event_btnhomeActionPerformed

    private void btnnotasmauseclicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnnotasmauseclicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnnotasmauseclicked

    private void btnnotasmouseexited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnnotasmouseexited

    }//GEN-LAST:event_btnnotasmouseexited

    private void btnnotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnotasActionPerformed
           frmNotas2 frmN = new frmNotas2();
        PanelPrincipal.add(frmN, "Notas");
     
        vista.show(PanelPrincipal, "Notas");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_btnnotasActionPerformed

    private void btnasistenciamauseclicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnasistenciamauseclicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnasistenciamauseclicked

    private void btnasistenciamouseexited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnasistenciamouseexited

    }//GEN-LAST:event_btnasistenciamouseexited

    private void btnasistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnasistenciaActionPerformed

       frmAsistencia frmA = new frmAsistencia();
        PanelPrincipal.add(frmA, "Asistencia");
        vista.show(PanelPrincipal, "Asistencia");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_btnasistenciaActionPerformed

    private void btnreportesmauseclicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnreportesmauseclicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnreportesmauseclicked

    private void btnreportesmouseexited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnreportesmouseexited

    }//GEN-LAST:event_btnreportesmouseexited

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel3MouseDragged
int xx,xy;
    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel3MousePressed

    private void btnreportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreportesActionPerformed
                   frmReportesNotas frmRN = new frmReportesNotas();
        PanelPrincipal.add(frmRN, "ReporteNotas");
     
        vista.show(PanelPrincipal, "ReporteNotas");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_btnreportesActionPerformed
    private void pegarImagenes() {
      //  ImageIcon imagen = new ImageIcon("src/IMG/slider2.jpg");
     //   Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(lbslider.getWidth(), lbslider.getHeight(), Image.SCALE_DEFAULT));
     // PanelPrincipal.setIcon(icono);
        this.repaint();
        Icon icon0 = new ImageIcon("src/IMG/cerrar.png");
        Icon icon1 = new ImageIcon("src/IMG/home.png");
        Icon icon2 = new ImageIcon("src/IMG/asistencia.png");
        Icon icon3 = new ImageIcon("src/IMG/notas.png");
        Icon icon4 = new ImageIcon("src/IMG/reportes.png");
        btncerrar.setIcon(icon0);
        btnhome.setIcon(icon1);
        btnasistencia.setIcon(icon2);
        btnnotas.setIcon(icon3);
        btnreportes.setIcon(icon3);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JPanel PanelPrincipal;
    private javax.swing.JButton btnasistencia;
    private javax.swing.JButton btncerrar;
    private javax.swing.JButton btncerrar1;
    private javax.swing.JButton btncerrar2;
    private javax.swing.JButton btnhome;
    private javax.swing.JButton btnnotas;
    private javax.swing.JButton btnreportes;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbusuario;
    private javax.swing.JLabel lbusuario1;
    private javax.swing.JLabel lbusuario2;
    private javax.swing.JLabel lbusuario3;
    // End of variables declaration//GEN-END:variables
}
