/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Cache.UserLoginCache;
import Entidad.E_Usuario;
import java.awt.CardLayout;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;
import javax.swing.*;
import java.awt.*;
import java.lang.*;
import java.net.*;

/**
 *
 * @author Administrador
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    //   frmPrueba Prueba = new frmPrueba();
    CardLayout vista;
    frmAsistencia frmA = new frmAsistencia();
    frmNotas2 frmN = new frmNotas2();
    frmUsuario frmU = new frmUsuario();
    frmHome frmH = new frmHome();
    static E_Usuario obj = new E_Usuario();

    public frmMain(E_Usuario obj) {
        initComponents();

        setSize(950, 600);
        JOptionPane.showMessageDialog(null,"Bienvenido(a) "+obj.getNombre());

        loaddata(obj);
        pegarImagenes();
        this.setLocationRelativeTo(null);
        vista = (CardLayout) PanelPrincipal.getLayout();

        PanelPrincipal.add(frmH, "Home");
        vista.show(PanelPrincipal, "Home");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        btncerrar = new javax.swing.JButton();
        btncerrar1 = new javax.swing.JButton();
        btncerrar2 = new javax.swing.JButton();
        lbusuario = new javax.swing.JLabel();
        lbnombre = new javax.swing.JLabel();
        btnhome = new javax.swing.JButton();
        btnnotas = new javax.swing.JButton();
        btnasistencia = new javax.swing.JButton();
        btnUsuario = new javax.swing.JButton();
        lbusuario2 = new javax.swing.JLabel();
        lbadmin = new javax.swing.JLabel();
        btnreportes1 = new javax.swing.JButton();
        btnconfig = new javax.swing.JButton();
        PanelPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(950, 600));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setPreferredSize(new java.awt.Dimension(900, 160));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });

        btncerrar.setBackground(new java.awt.Color(0, 0, 0));
        btncerrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btncerrar.setContentAreaFilled(false);
        btncerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncerrarActionPerformed(evt);
            }
        });

        btncerrar1.setBackground(new java.awt.Color(0, 0, 0));
        btncerrar1.setContentAreaFilled(false);
        btncerrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncerrar1ActionPerformed(evt);
            }
        });

        btncerrar2.setBackground(new java.awt.Color(0, 0, 0));
        btncerrar2.setContentAreaFilled(false);
        btncerrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncerrar2ActionPerformed(evt);
            }
        });

        lbusuario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbusuario.setForeground(new java.awt.Color(255, 255, 255));
        lbusuario.setText("Usuario:");

        lbnombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbnombre.setForeground(new java.awt.Color(255, 255, 255));
        lbnombre.setText("José Luis Arias Flores");

        btnhome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnhome.setForeground(new java.awt.Color(255, 255, 255));
        btnhome.setText("HOME");
        btnhome.setContentAreaFilled(false);
        btnhome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnhome.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnhome.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnhome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mauseclicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseexited(evt);
            }
        });
        btnhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomeActionPerformed(evt);
            }
        });

        btnnotas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnnotas.setForeground(new java.awt.Color(255, 255, 255));
        btnnotas.setText("NOTAS");
        btnnotas.setContentAreaFilled(false);
        btnnotas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnnotas.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnnotas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnnotas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mauseclicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseexited(evt);
            }
        });
        btnnotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnotasActionPerformed(evt);
            }
        });

        btnasistencia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnasistencia.setForeground(new java.awt.Color(255, 255, 255));
        btnasistencia.setText("ASISTENCIA");
        btnasistencia.setContentAreaFilled(false);
        btnasistencia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnasistencia.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnasistencia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnasistencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mauseclicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseexited(evt);
            }
        });
        btnasistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnasistenciaActionPerformed(evt);
            }
        });

        btnUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnUsuario.setText("USUARIO");
        btnUsuario.setContentAreaFilled(false);
        btnUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUsuario.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnUsuario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mauseclicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseexited(evt);
            }
        });
        btnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioActionPerformed(evt);
            }
        });

        lbusuario2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbusuario2.setForeground(new java.awt.Color(255, 255, 255));
        lbusuario2.setText("Cargo:");

        lbadmin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbadmin.setForeground(new java.awt.Color(255, 255, 255));
        lbadmin.setText("Admin");

        btnreportes1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnreportes1.setForeground(new java.awt.Color(255, 255, 255));
        btnreportes1.setText("REPORTES");
        btnreportes1.setContentAreaFilled(false);
        btnreportes1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnreportes1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnreportes1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnreportes1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnreportes1mauseclicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnreportes1mouseexited(evt);
            }
        });
        btnreportes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreportes1ActionPerformed(evt);
            }
        });

        btnconfig.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnconfig.setForeground(new java.awt.Color(255, 255, 255));
        btnconfig.setContentAreaFilled(false);
        btnconfig.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnconfig.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnconfig.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnconfig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnconfigmauseclicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnconfigmouseexited(evt);
            }
        });
        btnconfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconfigActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btnhome, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lbusuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbnombre))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnasistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnnotas, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnreportes1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lbusuario2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbadmin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                        .addComponent(btncerrar2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btncerrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btncerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnconfig, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btncerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncerrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncerrar2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnconfig, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbusuario)
                    .addComponent(lbnombre)
                    .addComponent(lbusuario2)
                    .addComponent(lbadmin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnhome, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnnotas, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnasistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnreportes1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_START);

        PanelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        PanelPrincipal.setLayout(new java.awt.CardLayout());
        getContentPane().add(PanelPrincipal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncerrarActionPerformed
        dispose();
    }//GEN-LAST:event_btncerrarActionPerformed

    private void btncerrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncerrar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncerrar1ActionPerformed

    private void btncerrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncerrar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncerrar2ActionPerformed
    int xx, xy;
    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel3MousePressed
    /*
    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {                                     
        xx = evt.getX();
        xy = evt.getY();
    }                                    
     */
    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel3MouseDragged


    private void mauseclicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mauseclicked
        // TODO add your handling code here:

    }//GEN-LAST:event_mauseclicked

    private void mouseexited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseexited

    }//GEN-LAST:event_mouseexited

    private void btnhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomeActionPerformed
        PanelPrincipal.add(frmH, "Home");
        //   PanelPrincipal.add(frmF, "Ficha");
        vista.show(PanelPrincipal, "Home");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
        //  PanelPrincipal.setVisible(true);

    }//GEN-LAST:event_btnhomeActionPerformed

    public void loaddata(E_Usuario usuario) {
        lbnombre.setText(usuario.getNombre());
        lbadmin.setText(usuario.getCargo());
    }
    private void btnasistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnasistenciaActionPerformed
        // TODO add your handling code here:
        PanelPrincipal.add(frmA, "Asistencia");
        vista.show(PanelPrincipal, "Asistencia");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_btnasistenciaActionPerformed

    private void btnnotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnotasActionPerformed
        PanelPrincipal.add(frmN, "Notas");
        //   PanelPrincipal.add(frmF, "Ficha");
        vista.show(PanelPrincipal, "Notas");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_btnnotasActionPerformed

    private void btnreportes1mauseclicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnreportes1mauseclicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnreportes1mauseclicked

    private void btnreportes1mouseexited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnreportes1mouseexited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnreportes1mouseexited

    private void btnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioActionPerformed

        PanelPrincipal.add(frmU, "Usuario");
        //   PanelPrincipal.add(frmF, "Ficha");
        vista.show(PanelPrincipal, "Usuario");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_btnUsuarioActionPerformed

    private void btnconfigmauseclicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnconfigmauseclicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnconfigmauseclicked

    private void btnconfigmouseexited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnconfigmouseexited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnconfigmouseexited

    private void btnconfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconfigActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnconfigActionPerformed

    private void btnreportes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreportes1ActionPerformed
        frmReportesNotas frmRN = new frmReportesNotas();
        PanelPrincipal.add(frmRN, "ReporteNotas");

        vista.show(PanelPrincipal, "ReporteNotas");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();       
    }//GEN-LAST:event_btnreportes1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain(obj).setVisible(true);
            }
        });
    }

    private void pegarImagenes() {
        //  ImageIcon imagen = new ImageIcon("src/IMG/slider2.jpg");
        //  Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(lbslider.getWidth(), lbslider.getHeight(), Image.SCALE_DEFAULT));
        //   lbslider.setIcon(icono);
//        this.repaint();

        Icon icon0 = new ImageIcon("src/IMG/cerrar.png");
        Icon icon1 = new ImageIcon("src/IMG/home.png");
        Icon icon2 = new ImageIcon("src/IMG/asistencia.png");
        Icon icon3 = new ImageIcon("src/IMG/notas.png");
        Icon icon4 = new ImageIcon("src/IMG/reportes.png");
        Icon icon5 = new ImageIcon("src/IMG/usuario.png");
        Icon icon6 = new ImageIcon("src/IMG/config.png");

        btncerrar.setIcon(icon0);
        btnhome.setIcon(icon1);
        btnasistencia.setIcon(icon2);
        btnnotas.setIcon(icon3);
        btnreportes1.setIcon(icon4);
        btnUsuario.setIcon(icon5);
        btnconfig.setIcon(icon6);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JPanel PanelPrincipal;
    private javax.swing.JButton btnUsuario;
    private javax.swing.JButton btnasistencia;
    private javax.swing.JButton btncerrar;
    private javax.swing.JButton btncerrar1;
    private javax.swing.JButton btncerrar2;
    private javax.swing.JButton btnconfig;
    private javax.swing.JButton btnhome;
    private javax.swing.JButton btnnotas;
    private javax.swing.JButton btnreportes1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbadmin;
    private javax.swing.JLabel lbnombre;
    private javax.swing.JLabel lbusuario;
    private javax.swing.JLabel lbusuario2;
    // End of variables declaration//GEN-END:variables
}
