/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import java.awt.CardLayout;
import javax.swing.SwingUtilities;

/**
 *
 * @author Administrador
 */
public class frmNotas1 extends javax.swing.JPanel {

    /**
     * Creates new form frmNotas1
     */
  
    public frmNotas1() {
        initComponents();
          
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(500, 352));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelPrincipal1.setLayout(new java.awt.CardLayout());
        add(PanelPrincipal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1459, 384, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 129, 627, 173));

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox1.setText("Revisado");
        add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(616, 67, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Curso:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 37, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PROGRAMACION I", "PROGRAMACION II", "GESTION DE TI" }));
        add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 67, 150, 30));
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 67, -1, 30));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 67, 170, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "UNIDAD I", "UNIDAD II", "UNIDAD III" }));
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 67, 150, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Unidad:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 37, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Buscar Alumno:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 37, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
  //  p1.setVisible(true);
    }//GEN-LAST:event_jTable1MousePressed
 //frmFichaTutoria frmF=new frmFichaTutoria();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelPrincipal1;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    private void setLocationRelativeTo(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
