/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Datos.ClsConexion;
import Datos.D_Ficha;
import Datos.D_Notas;
import Datos.D_Notas2;
import Entidad.E_Ficha;
import Entidad.E_Notas;
import static Presentacion.frmMain.PanelPrincipal;
import java.awt.CardLayout;
import java.sql.Connection;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrador
 */
public class frmNotas2 extends javax.swing.JPanel {

    /**
     * Creates new form frmNotas2
     */
    CardLayout vista;

    ClsConexion conect = new ClsConexion();
    Connection cn = conect.conectar();

    public frmNotas2() {
        initComponents();
        //    actualizar();
        mostrar("");
        listarcb();

        this.setSize(950, 440);
        vista = (CardLayout) (PanelPrincipal.getLayout());

    }

    public void p3cargar() {
        D_Notas2 func = new D_Notas2();
        DefaultTableModel modelo2;
        //    E_Notas dts=new E_Notas();
        //     dts.setCod_alum(cod_alum);
        lbcodalum.setText(cod_alum);
        lbnombre.setText(nombre);
        lbciclo.setText(ciclo);
        modelo2 = func.listarestudiante(cod_alum);
        Tablalistado2.setModel(modelo2);
        //
        lbnombre3.setText(nombre);
        lbfecha.setText(String.valueOf(dateFormat.format(date)));
    }
    public void p4cargar(){
         D_Ficha func = new D_Ficha();
        DefaultTableModel modelo3;
        modelo3 = func.listarficha(cod_alum);
        Tablalistado3.setModel(modelo3);
    }

    public void actualizar() {

        D_Notas2 func = new D_Notas2();
        DefaultTableModel modelo;
        modelo = func.mostrar("");
        Tablalistado.setModel(modelo);
    }

    void mostrar(String buscar) {
        try {
            DefaultTableModel modelo;
            D_Notas2 func = new D_Notas2();
            modelo = func.mostrar(buscar);

            Tablalistado.setModel(modelo);
            //     lblTotalRegistros.setText("Total registros " + Integer.toString(func.totalregistros));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public void listarcb() {
        E_Notas cliente = new E_Notas();

        cliente.listarcursos(cbcursos);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        p1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tablalistado = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        cbcursos = new javax.swing.JComboBox<>();
        txtBuscar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbunidad = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        txtver = new javax.swing.JButton();
        btnrevisar1 = new javax.swing.JButton();
        p2 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lbfecha = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtoa = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        lbnombre3 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtaa = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtop = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtpp = new javax.swing.JTextArea();
        jLabel21 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtap = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtpa = new javax.swing.JTextArea();
        jButton6 = new javax.swing.JButton();
        p3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbcodalum = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        lbciclo = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbnombre = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        Tablalistado2 = new javax.swing.JTable();
        jLabel32 = new javax.swing.JLabel();
        p4 = new javax.swing.JPanel();
        btnback1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tablalistado3 = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        PanelPrincipal.setLayout(new java.awt.CardLayout());

        p1.setBackground(new java.awt.Color(0, 102, 204));
        p1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tablalistado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tablalistado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TablalistadoMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(Tablalistado);

        p1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 810, 240));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Curso:");
        p1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, -1, -1));

        cbcursos.setBackground(new java.awt.Color(102, 102, 102));
        cbcursos.setForeground(new java.awt.Color(255, 255, 255));
        p1.add(cbcursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 150, 30));

        txtBuscar.setBackground(new java.awt.Color(255, 255, 255));
        txtBuscar.setForeground(new java.awt.Color(0, 0, 0));
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });
        p1.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 170, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("N° Cursos Desaprobados:");
        p1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Buscar Alumno:");
        p1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        cbunidad.setBackground(new java.awt.Color(102, 102, 102));
        cbunidad.setForeground(new java.awt.Color(255, 255, 255));
        p1.add(cbunidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 150, 30));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Unidad:");
        p1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, -1, -1));
        p1.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, -1, -1));

        txtver.setText("Ver");
        txtver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtverActionPerformed(evt);
            }
        });
        p1.add(txtver, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 190, -1, -1));

        btnrevisar1.setText("REVISADO");
        btnrevisar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrevisar1ActionPerformed(evt);
            }
        });
        p1.add(btnrevisar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 140, -1, -1));

        PanelPrincipal.add(p1, "card2");

        p2.setBackground(new java.awt.Color(255, 255, 153));

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Temas o problemas que se trataron en la sesión");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 129, -1, -1));

        jLabel14.setBackground(new java.awt.Color(0, 0, 0));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Fecha:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 91, -1, -1));

        lbfecha.setBackground(new java.awt.Color(0, 0, 0));
        lbfecha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbfecha.setForeground(new java.awt.Color(255, 255, 255));
        lbfecha.setText("14/12/2020");
        jPanel2.add(lbfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(768, 91, -1, -1));

        jLabel16.setBackground(new java.awt.Color(0, 0, 0));
        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Acuerdos y/o Soluciones resultantes de la Sesion");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 262, -1, -1));

        jTextArea5.setColumns(20);
        jTextArea5.setRows(5);
        jTextArea5.setText("Academicos");
        txtoa.setViewportView(jTextArea5);

        jPanel2.add(txtoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 290, -1));

        jLabel17.setBackground(new java.awt.Color(0, 0, 0));
        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Nombre del Tutorado:");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 91, -1, -1));

        lbnombre3.setBackground(new java.awt.Color(0, 0, 0));
        lbnombre3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbnombre3.setForeground(new java.awt.Color(255, 255, 255));
        lbnombre3.setText("José Luis Arias Flores");
        jPanel2.add(lbnombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, -1, -1));

        jLabel19.setBackground(new java.awt.Color(0, 0, 0));
        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Observaciones sobre la Sesion");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 395, -1, -1));

        jLabel20.setBackground(new java.awt.Color(0, 0, 0));
        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("01");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(798, 64, -1, -1));

        txtaa.setColumns(20);
        txtaa.setRows(5);
        txtaa.setText("Academicos");
        jScrollPane3.setViewportView(txtaa);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 290, -1));

        txtop.setColumns(20);
        txtop.setRows(5);
        txtop.setText("Personales");
        jScrollPane6.setViewportView(txtop);

        jPanel2.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 430, 290, -1));

        txtpp.setColumns(20);
        txtpp.setRows(5);
        txtpp.setText("Personales");
        jScrollPane4.setViewportView(txtpp);

        jPanel2.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(554, 167, 290, -1));

        jLabel21.setBackground(new java.awt.Color(0, 0, 0));
        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Ing. Liliana Vega Bernal");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, -1, -1));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FICHA TUTORIA");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 14, -1, -1));

        jLabel22.setBackground(new java.awt.Color(0, 0, 0));
        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("N°:");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(772, 64, -1, -1));

        jLabel23.setBackground(new java.awt.Color(0, 0, 0));
        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Nombre del Tutor:");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, -1, -1));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("REGISTRAR");
        jButton2.setOpaque(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 543, 157, 57));

        txtap.setColumns(20);
        txtap.setRows(5);
        txtap.setText("Personales");
        jScrollPane7.setViewportView(txtap);

        jPanel2.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 300, 290, -1));

        txtpa.setColumns(20);
        txtpa.setRows(5);
        txtpa.setText("Academicos");
        jScrollPane8.setViewportView(txtpa);

        jPanel2.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 167, 290, -1));

        jButton6.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jButton6.setText("<");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jScrollPane9.setViewportView(jPanel2);

        javax.swing.GroupLayout p2Layout = new javax.swing.GroupLayout(p2);
        p2.setLayout(p2Layout);
        p2Layout.setHorizontalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
        );
        p2Layout.setVerticalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
        );

        PanelPrincipal.add(p2, "card3");

        p3.setBackground(new java.awt.Color(0, 102, 204));
        p3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nombre:");
        p3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("910173075");
        p3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Telefono:");
        p3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Codigo:");
        p3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Carrera Profesional:");
        p3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, -1, -1));

        lbcodalum.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbcodalum.setForeground(new java.awt.Color(255, 255, 255));
        lbcodalum.setText("2017058805");
        p3.add(lbcodalum, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, -1, -1));

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("VER FICHAS TUTORIAS");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        p3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, 220, 40));

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("REGISTRAR FICHA TUTORIA");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        p3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, 220, 50));

        btnback.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnback.setText("<");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        p3.add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        lbciclo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbciclo.setForeground(new java.awt.Color(255, 255, 255));
        lbciclo.setText("0");
        p3.add(lbciclo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Ciclo:");
        p3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, -1, -1));

        lbnombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbnombre.setForeground(new java.awt.Color(255, 255, 255));
        lbnombre.setText("ING. DE SISTEMAS");
        p3.add(lbnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, -1));

        Tablalistado2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(Tablalistado2);

        p3.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, 160));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("ING. DE SISTEMAS");
        p3.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, -1, -1));

        PanelPrincipal.add(p3, "card4");

        p4.setBackground(new java.awt.Color(0, 102, 204));
        p4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnback1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnback1.setText("<");
        btnback1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnback1ActionPerformed(evt);
            }
        });
        p4.add(btnback1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        Tablalistado3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(Tablalistado3);

        p4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, 280));

        PanelPrincipal.add(p4, "card5");

        add(PanelPrincipal, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void TablalistadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablalistadoMousePressed

        int fila = Tablalistado.rowAtPoint(evt.getPoint());
        nombre = (Tablalistado.getValueAt(fila, 1).toString());
        ciclo = (Tablalistado.getValueAt(fila, 2).toString());
        estado = (Tablalistado.getValueAt(fila, 3).toString());
        cod_alum = (Tablalistado.getValueAt(fila, 0).toString());
    //    JOptionPane.showMessageDialog(null, cod_alum + estado);
        /*
        PanelPrincipal.add(p3, "p3");
        vista.show(PanelPrincipal, "p3");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint(); */
    }//GEN-LAST:event_TablalistadoMousePressed
    String estado;
    String cod_alum;
    String nombre;
    String ciclo;
    String Unidad;
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        PanelPrincipal.add(p3, "p3");
        vista.show(PanelPrincipal, "p3");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        // TODO add your handling code here:
        mostrar(txtBuscar.getText());
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void txtverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtverActionPerformed
        // TODO add your handling code here:
        PanelPrincipal.add(p3, "p3");
        vista.show(PanelPrincipal, "p3");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
        p3cargar();
    }//GEN-LAST:event_txtverActionPerformed

    private void btnrevisar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrevisar1ActionPerformed
        E_Notas dts = new E_Notas();
        D_Notas2 func = new D_Notas2();
        dts.setEstado("0");
        dts.setCod_alum(cod_alum);
        JOptionPane.showMessageDialog(null, "MODIFICADO");
        //  JOptionPane.showMessageDialog(null,cod_alum+estado);
        func.editarestado(dts);
        actualizar();
    }//GEN-LAST:event_btnrevisar1ActionPerformed
      Date date = new Date();

        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");  
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     //       Date date = new Date();

     //   DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");     
        E_Ficha dts = new E_Ficha();
        D_Ficha func = new D_Ficha();
        
        dts.setCod_alum(cod_alum);
        dts.setProblema_academico(txtpa.getText());
        dts.setProblema_personal(txtpp.getText());
         dts.setAcuerdo_academico(txtaa.getText());
        dts.setAcuerdo_personal(txtap.getText());
        dts.setObservacion_academico(txtop.getText());
        dts.setObservacion_personal(txtop.getText());
        dts.setNombre("LILIANA VEGA BERNAL");
        dts.setFecha(String.valueOf(dateFormat.format(date)));
        
        JOptionPane.showMessageDialog(null, "Registrado Correctamente");
        func.insertarficha(dts);
     //   actualizar();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        PanelPrincipal.add(p1, "p2");
        vista.show(PanelPrincipal, "p2");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_btnbackActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        PanelPrincipal.add(p2, "p2");
        vista.show(PanelPrincipal, "p2");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnback1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnback1ActionPerformed
              PanelPrincipal.add(p3, "p3");
        vista.show(PanelPrincipal, "p3");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_btnback1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       PanelPrincipal.add(p4, "p4");
        vista.show(PanelPrincipal, "p4");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
        p4cargar();
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JTable Tablalistado;
    private javax.swing.JTable Tablalistado2;
    private javax.swing.JTable Tablalistado3;
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnback1;
    private javax.swing.JButton btnrevisar1;
    private javax.swing.JComboBox<E_Notas> cbcursos;
    private javax.swing.JComboBox<E_Notas> cbunidad;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JLabel lbciclo;
    private javax.swing.JLabel lbcodalum;
    private javax.swing.JLabel lbfecha;
    private javax.swing.JLabel lbnombre;
    private javax.swing.JLabel lbnombre3;
    private javax.swing.JPanel p1;
    private javax.swing.JPanel p2;
    private javax.swing.JPanel p3;
    private javax.swing.JPanel p4;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextArea txtaa;
    private javax.swing.JTextArea txtap;
    private javax.swing.JScrollPane txtoa;
    private javax.swing.JTextArea txtop;
    private javax.swing.JTextArea txtpa;
    private javax.swing.JTextArea txtpp;
    private javax.swing.JButton txtver;
    // End of variables declaration//GEN-END:variables
}
