/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Datos.ClsConexion;
import java.awt.BorderLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.swing.JRViewer;


/**
 *
 * @author Administrador
 */
public class frmReportesNotas extends javax.swing.JPanel {

    /**
     * Creates new form frmReportesNotas
     */
    public frmReportesNotas() {
        initComponents();
        Connect();
    }
    Connection con;
     PreparedStatement pst;
    public void Connect(){
          Connection link = null;
        try {

            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:33065/sepis","root","");
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null, "Error al conectar con la base de datos" + e);
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtcod_alum = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(0, 102, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnver.setText("jButton1");
        btnver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnverActionPerformed(evt);
            }
        });
        add(btnver, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 53, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Alumno:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        txtcod_alum.setBackground(new java.awt.Color(255, 255, 255));
        txtcod_alum.setForeground(new java.awt.Color(0, 0, 0));
        txtcod_alum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcod_alumKeyReleased(evt);
            }
        });
        add(txtcod_alum, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 170, 30));
        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 950, 510));
    }// </editor-fold>//GEN-END:initComponents

    private void btnverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnverActionPerformed
        loadreport();
    }//GEN-LAST:event_btnverActionPerformed

    private void txtcod_alumKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcod_alumKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtcod_alumKeyReleased

    public void loadreport(){
        
        try {
             
            HashMap a=new HashMap();
            a.put("cod_a", txtcod_alum.getText());
            jPanel1.removeAll();
            jPanel1.repaint();
            jPanel1.revalidate();
            JasperDesign jdesign = JRXmlLoader.load("C:\\Users\\Administrador\\Desktop\\VII CICLO\\PROGRA III\\PROYECTO SEPIS\\SEPIS\\src\\main\\java\\Presentacion\\report1.jrxml");
            JasperReport jreports=JasperCompileManager.compileReport(jdesign);
            JasperPrint jprint=JasperFillManager.fillReport(jreports, a, con);
            JRViewer v=new JRViewer(jprint);
            jPanel1.setLayout(new BorderLayout());
            jPanel1.add(v);
            
        } catch (JRException ex) {
            Logger.getLogger(frmReportesNotas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtcod_alum;
    // End of variables declaration//GEN-END:variables
}
